import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "../components/Cabecalho/index.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Entrega - 4",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
